version: "3.9"
services:
  db:
    image: postgres:15-alpine
    container_name: daycare-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: daycare_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  app:
    image: anasilva2696/playsafe-svc:latest
    container_name: daycare-app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      # Override DATABASE_URL if needed, pointing to the db container
      DATABASE_URL: postgres://postgres:admin@db:5432/daycare_db
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  pgdata:
