version: "3.9"
services:
  db:
    image: postgres:15-alpine
    container_name: daycare-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: daycare_db
    ports:
      - "5432:5432"
    volumes:
       - pgdata:/var/lib/postgresql/data
       - ./db-init:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: daycare-app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: ["node", "src/app.js"]

volumes:
  pgdata:
