apiVersion: v1
kind: ConfigMap
metadata:
  name: playsafe-config
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "admin"
  DB_NAME: "daycare_db"
  JWT_SECRET: "super_secret_jwt"
