apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: playsafe-api-hpa
 namespace: playsafe
spec:
 scaleTargetRef:
  apiVersion: apps/v1
  kind: Deployment
  name: playsafe-api
 minReplicas: 1
 maxReplicas: 5
 metrics:
  - type: Resource
    resource:
     name: cpu
     target:
      type: Utilization
      averageUtilization: 20
 behavior:
  scaleDown:
   stabilizationWindowSeconds: 60
   policies:
    - type: Percent
      value: 100
      periodSeconds: 60
